apps/course/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path
from course.views import *

urlpatterns = [
    path('', show_course, name='course'),
    path('chapter/<int:c_id>/', show_chapter, name='chapter'),
    path('course/<int:c_id>', show_chapter_list, name='chapter_list'),
    path('chapter/video/<int:v_id>/', video_play, name='chapter_video'),
    path('chapter/ajax/', chapter_ajax_page, name='chapter_ajax'),

]

huima/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.urls import re_path
from django.views.static import serve
from .settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.index.urls', 'index'), namespace='index')),  # wjl
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('course/', include('apps.course.urls')),
    path('subject/', include('apps.subject.urls')),
    path('task/', include('apps.task.urls')),
    path('usercenter/', include('apps.user.urls')),
    re_path(r"media/(?P<path>.*)$", serve, {'document_root': MEDIA_ROOT}),

]

apps/course/models.py
from django.db import models
from datetime import datetime
from user.models import User
from subject.models import ProjectDetail
from blog.models import Blog


# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=20, verbose_name='课程名称', default='')
    need_time = models.IntegerField(default=0, verbose_name='需要时长')  # 需要时长
    synopsis = models.CharField(max_length=50, verbose_name='课程简介')  # 课程简介
    study_len = models.IntegerField(default=0, verbose_name='学习人数')  # 有多少人学习
    career_direction = models.CharField(max_length=50, verbose_name='职业方向标签', default='全部')
    classification = models.CharField(max_length=50, verbose_name='分类标签', default='全部')
    cover = models.ImageField(max_length=100, verbose_name='课程封面', null=True, upload_to='course/')  # 课程封面
    leave = models.IntegerField(null=True, default=1, verbose_name='难易程度',
                                choices=((1, '入门'), (2, '初级'), (3, '中级'), (4, '高级')))
    status = models.IntegerField(choices=((0, '下架'), (1, '上架')), null=True, default=1, verbose_name='课程当前状态')
    buy = models.IntegerField(choices=((0, '未购买'), (1, '已购买')), default=0, verbose_name='是否购买课程')
    buy_channel = models.IntegerField(choices=((1, '支付宝'), (2, '微信'), (3, '信用卡'), (4, '储蓄卡'), (5, '积分兑换')),
                                      verbose_name='购买渠道', default=1)
    create_times = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    score = models.IntegerField(verbose_name='评分', default=5)
    project_id = models.ManyToManyField(ProjectDetail, verbose_name='相关项目')

    class Meta:
        verbose_name = '课程表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Chapter(models.Model):
    name = models.CharField(max_length=50, blank=True, verbose_name='章节名称')
    synopsis = models.CharField(max_length=300, null=True, verbose_name='章节简介')
    num = models.CharField(max_length=30, default='第一章')
    course_id = models.ForeignKey('Course', verbose_name='所属的课程id', on_delete=models.DO_NOTHING, blank=True)
    knowledge = models.ImageField(verbose_name='思维导图(知识点)', null='', blank='', default='')
    blog = models.ManyToManyField(Blog, verbose_name='相关博客',blank=True)

    create_times = models.DateTimeField(verbose_name='创建时间', default=datetime.now)
    up_time = models.DateTimeField(verbose_name='修改时间', auto_now=True)
    status = models.IntegerField(choices=((0, '未完成'), (1, '已完成')), default=0, verbose_name='章节完成度')

    class Meta:
        verbose_name = '章节表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Video(models.Model):
    name = models.CharField(max_length=200, blank=True, verbose_name='视频名称')
    synopsis = models.CharField(max_length=300, null=True, verbose_name='视频简介')
    cover = models.ImageField(max_length=100, verbose_name='视频封面', null=True, upload_to='course/video/img/')
    need_time = models.IntegerField(verbose_name='视频时长')
    video_type = models.IntegerField(((1, '项目视频'), (2, '课程视频')), blank=True, default=2)
    url = models.FileField(max_length=200, verbose_name='视频地址', upload_to='course/video/video/')
    create_times = models.DateTimeField(verbose_name='创建时间', default=datetime.now)
    chapter_id = models.ForeignKey('Chapter', verbose_name='所属章节id', on_delete=models.DO_NOTHING, blank=True)

    class Meta:
        verbose_name = '视频表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Note(models.Model):
    name = models.CharField(max_length=50, null=True)
    chapter_id = models.ForeignKey('Chapter', verbose_name='所属章节id', on_delete=models.DO_NOTHING, blank=True)
    inner = models.CharField(max_length=300, blank=True, verbose_name='笔记内容')
    status = models.IntegerField(choices=((0, '屏蔽'), (1, '展示')), default=1, verbose_name='当前状态')
    user_id = models.ForeignKey(User, verbose_name='用户id', on_delete=models.DO_NOTHING, blank=True)
    create_times = models.DateTimeField(verbose_name='创建时间', default=datetime.now)

    class Meta:
        verbose_name = '笔记表'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

apps/subject/models.py
from django.db import models

# Create your models here.
# 项目详细表
class ProjectDetail(models.Model):

    proj_name = models.CharField(max_length=200, verbose_name='项目名称')
    proj_desc = models.CharField(verbose_name="项目简介", max_length=1024)
    # 大项目分割为小项目所以每个小项目有完成时间和状态
    proj_start = models.CharField(max_length=1024, verbose_name='项目开始', null=True, blank=True)
    proj_start_dt = models.DateTimeField(max_length=1024, verbose_name='项目开始完成时间', null=True, blank=True)
    proj_start_status = models.IntegerField(verbose_name='项目开始状态', choices=((0, '未完成'), (1, '完成')), default=0)

    proj_introduce = models.CharField(max_length=1024, verbose_name='功能介绍')
    proj_introduce_dt = models.DateTimeField(max_length=1024, verbose_name='功能介绍完成时间', null=True, blank=True)
    proj_introduce_status = models.IntegerField(verbose_name='功能介绍状态', choices=((0, '未完成'), (1, '完成')), default=0)

    proj_baseskill = models.CharField(max_length=1024, verbose_name='基础技能', null=True, blank=True)
    proj_baseskill_dt = models.DateTimeField(max_length=1024, verbose_name='基础技能完成时间', null=True, blank=True)
    proj_baseskill_status = models.IntegerField(verbose_name='基础技能状态', choices=((0, '未完成'), (1, '完成')), default=0)

    proj_display = models.CharField(max_length=1024, verbose_name='项目展示', null=True, blank=True)
    proj_display_dt = models.DateTimeField(max_length=1024, verbose_name='项目展示完成时间', null=True, blank=True)
    proj_display_status = models.IntegerField(verbose_name='项目展示状态', choices=((0, '未完成'), (1, '完成')), default=0)

    proj_aboutread = models.CharField(max_length=1024, verbose_name='相关阅读', null=True, blank=True)   # 外键字段
    proj_aboutread_dt = models.DateTimeField(max_length=1024, verbose_name='相关阅读完成时间', null=True, blank=True)
    proj_aboutread_status = models.IntegerField(verbose_name='相关阅读状态', choices=((0, '未完成'), (1, '完成')), default=0)

    proj_download = models.CharField(max_length=1024, verbose_name='资料下载', null=True, blank=True)
    proj_download_dt = models.DateTimeField(max_length=1024, verbose_name='资料下载完成时间', null=True, blank=True)
    proj_download_status = models.IntegerField(verbose_name='资料下载状态', choices=((0, '未完成'), (1, '完成')), default=0)

    proj_video = models.URLField(max_length=1024, verbose_name='相关视频', null=True, blank=True)  # 外键字段
    proj_video_dt = models.DateTimeField(max_length=1024, verbose_name='相关视频完成时间', null=True, blank=True)
    proj_video_status = models.IntegerField(verbose_name='相关视频状态', choices=((0, '未完成'), (1, '完成')), default=0)

    proj_upload = models.CharField(max_length=1024, verbose_name='上传项目', null=True, blank=True)
    proj_upload_dt = models.DateTimeField(max_length=1024, verbose_name='上传项目完成时间', null=True, blank=True)
    proj_upload_status = models.IntegerField(verbose_name='上传项目状态', choices=((0, '未完成'), (1, '完成')), default=0)

    proj_senior = models.CharField(max_length=1024, verbose_name='进阶教程', null=True, blank=True)  # 外键字段
    proj_senior_dt = models.DateTimeField(max_length=1024, verbose_name='进阶教程完成时间', null=True, blank=True)
    proj_senior_status = models.IntegerField(verbose_name='进阶教程状态', choices=((0, '未完成'), (1, '完成')), default=0)

    proj_finish = models.CharField(max_length=1024, verbose_name='项目终点', null=True, blank=True)
    proj_finish_status = models.IntegerField(verbose_name='进阶教程状态', choices=((0, '未完成'), (1, '完成')), default=0)
    # 保存图片 用于页面样式
    proj_arrowleft = models.ImageField(verbose_name='左箭头', null=True, blank=True, upload_to="media/project")
    proj_arrowright = models.ImageField(verbose_name='右箭头', null=True, blank=True, upload_to="media/project")
    proj_arrowdown = models.ImageField(verbose_name='下箭头', null=True, blank=True, upload_to="media/project")
    proj_arrowup = models.ImageField(verbose_name='上箭头', null=True, blank=True, upload_to="media/project")

    proj_date = models.DateTimeField(verbose_name='项目完成日期', null=True, blank=True)
    proj_statu = models.IntegerField(verbose_name='项目状态', choices=((0, '未完成'), (1, '完成')), default=0)
    proj_text = models.TextField(verbose_name="留言板", null=True, blank=True)    # 保留字段
    proj_bg_img = models.ImageField(verbose_name='项目背景图', null=True, blank=True, default="media/1.jpg")
    proj_progress = models.IntegerField(verbose_name="项目进度", default=0)
    project_level = (
        (0, "初级"),
        (1, "中级"),
        (2, "高级")
    )
    # 项目列表页字段
    proj_level = models.IntegerField(verbose_name="项目难度", choices=project_level, default=0)
    proj_student = models.IntegerField(verbose_name="学习人数", default=0)
    proj_teacher = models.CharField(max_length=1024, verbose_name="指导老师", null=True, blank=True)
    proj_tag = models.CharField(max_length=1024, verbose_name="项目标签", null=True, blank=True)
    proj_howlong = models.SmallIntegerField(verbose_name="项目时长", default=1)
    proj_cover = models.ImageField(verbose_name="项目背景", default="media/a.jpg", upload_to="media/project/")

    class Meta:
        verbose_name = '项目详细表'
        verbose_name_plural = verbose_name
        # db_tablespace = 'proj_date'
        # get_latest_by = 'proj_date'
        # managed = True
        # order_with_respect_to = 'proj_name'


    def __str__(self):
        return self.proj_name

apps/course/views.py
from django.shortcuts import render
from course.models import *
from django.http import JsonResponse
from operation.models import CourseComment
from .models import Video


# Create your views here.


def show_course(request):
    """
    课程展示页
    """
    course = Course.objects.all()
    return render(request, 'course/courseList.html', {'data': course})


def show_chapter_list(request, c_id):
    """章节列表页"""
    course = Course.objects.get(id=c_id)
    # chapters=course.chapter_set.all()
    contacts = CourseComment.objects.order_by('-id')
    pro = course.project_id.all()
    chapters = Chapter.objects.filter(course_id=1)
    return render(request, 'course/chapterList.html',
                  {'course': course, 'chapters': chapters, 'pro': pro, 'contacts': contacts})


def chapter_ajax_page(request):
    page = 1

    page_num = 2  # 每页显示条数
    contact_list = Course.objects.all()
    chapter_count = contact_list.count()
    contact_lists = contact_list.filter(id__range=[(page * page_num + 1) - page_num, page * page_num + 1]).values('id',
                                                                                                                  'name')
    page_all = chapter_count / page_num  # 总页码
    contact_lists = list(contact_lists)
    return JsonResponse(contact_lists, content_type="application/json", safe=False)
    # return HttpResponse(contact_lists)


def show_chapter(request, c_id=1):
    """章节详情页"""
    chapter = Chapter.objects.get(id=c_id)
    print(type(chapter))
    # 知识点

    # 博客
    blog = chapter.blog.all()

    # QA
    qa = chapter.chapterqa_set.all()

    # 任务
    # task = chapter.questionsbank_set.all()

    # 视频
    video = chapter.video_set.all()
    print('qa', qa)
    return render(request, 'course/chapter.html', {'chapter': chapter, 'video': video, 'qa': qa, 'blog': blog})


def video_play(request, v_id):
    """视频播放页"""

    video = Video.objects.filter(id=v_id)
    return render(request, 'course/video.html', {'data': ''})

templates/course/chapter.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}
    课程章节
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/course/chapter.css' %}">
{% endblock %}

{% block html_body %}
<div class="container-fluid  cha-inner-warp">
    <div class="container-fluid cha-header">
        <div class="container">
            <ol class="breadcrumb cha-nav">

            </ol>
            <h3>{{ chapter.0.name }}</h3>
            <p>{{ chapter.0.synopsis }}</p>
        </div>
    </div>
    <div class="container cha-inner">
        <div class="cha-inner-list">
            <span class="list-span span-active" attr="card1">视频资料</span>
            <span class="list-span" attr="card2">本章教程</span>
            <span class="list-span" attr="card3">课程小结</span>
            <span class="list-span" attr="card4">本章任务</span>
            <span class="list-span" attr="card5">QA问答</span>
        </div>
        <div class="cha-inner-list">
            <div class="card card1 card-show">
                <p class="det-name">
                    视频资料
                </p>
                <ul class="list-group cha-entry">
                    {% for foo in video %}
                         <li class="list-group-item">
                        <span class="iconfont">&#xe809;</span>&nbsp;&nbsp;<a href="#">{{ foo.name }}</a>
                    </li>
                    {% endfor %}

                </ul>
            </div>
            <div class="card card2">
                <p class="det-name">
                    本章教程
                </p>
                <ul class="list-group cha-entry">
                    {% for bl in blog %}
                        <li class="list-group-item">
                        <span class="iconfont">&#xe809;</span>&nbsp;&nbsp;<a  href="#">{{ bl.title }}</a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="card card3">
                <p class="det-name">
                    本章小结
                </p>
                <img src="{{ MEDIA_URL }}{{ chapter.knowledge }}" alt="">
            </div>
            <div class="card card4 ">
                <p>本章任务</p>
                <ul class="list-group">
                    <li class="list-group-item chapter_task"><span>这是一大串的测试数据，仅供测试</span></li>
                    <li class="list-group-item chapter_task"><span>这是一大串的测试数据，仅供测试</span></li>
                    <li class="list-group-item chapter_task"><span>这是一大串的测试数据，仅供测试</span></li>
                    <li class="list-group-item chapter_task"><span>这是一大串的测试数据，仅供测试</span></li>
                </ul>
            </div>
            <div class="card card5">
                <p class="det-name">
                    看看大家有什么问题
                </p>
                <ul class="list-group cha-entry">
                    {% for questions in qa %}
                        <li class="list-group-item"><span class="def-user">Q：</span>&nbsp;&nbsp;<span>{{ questions.question }}</span></li>
                        <li class="list-group-item"><span class="def-user">A：</span>&nbsp;&nbsp;<span>{{ questions.answer }}</span></li>
                    {% endfor %}
                </ul>
            </div>

        </div>
    </div>


</div>
{% endblock %}

{% block small_js %}
<script>
    $(function () {
        $('.list-span').on('click', function () {
            var div = $(this).attr('attr');
            $('.card-show').removeClass('card-show');
            $('.' + div).addClass('card-show');
        })
    })
</script>
{% endblock %}

templates/course/chapterList.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}
    课程章节
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/course/chapterList.css' %}">
{% endblock %}


{% block html_body %}
    {% csrf_token %}
    <div class="container-fluid  cha-inner-warp">
        <div class="container-fluid cha-header">
            <div class="container">
                <ol class="breadcrumb cha-nav">
                    {#                    <li><a href="#">首页</a></li>#}
                    {#                    <li class="active">{{ course.name }}</li>#}
                </ol>
                <h1>{{ course.name }}</h1>
                <ul>
                    <li>难度&nbsp;&nbsp;<span class="cha-nav-data">{{ course.get_leave_display }}</span></li>
                    ·
                    <li>时长&nbsp;&nbsp;<span class="cha-nav-data">{{ course.need_time }}</span></li>
                    ·
                    <li>学习人数&nbsp;&nbsp;<span class="cha-nav-data">{{ course.study_len }}</span></li>
                    ·
                    <li>综合评分&nbsp;&nbsp;<span class="cha-nav-data">{{ course.score }}</span></li>
                </ul>
            </div>
        </div>
        <div class="container cha-inner">
            <div class="cha-inner-list">
                简介：{{ course.synopsis }}
            </div>
            <div class="cha-inner-list">
                <p class="cha-name">
                    章节展示
                </p>
                <ul class="list-group cha-list-color list_border">
                    {% for chapter in chapters %}
                        <li class="list-group-item">
                            <p><a href="{% url 'chapter' chapter.id %}">{{ chapter.num }} {{ chapter.name }}</a>
                                {% if chapter.status == 1 %}
                                    <span class="studied">已完成</span>
                                {% endif %}
                            </p>
                            <p>{{ chapter.synopsis }}</p>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="cha-inner-list">
                <p class="cha-name">相关项目</p>

                <div class=" cha-scrollBar">
                    <div id='cha-scrollBar-list' class=" cha-scrollBar-list">
                        {% for foo in pro %}
                            <a class=" l-sec">
                                <img class="l-sec-img" src="{{ MEDIA_URL }}{{ foo.proj_bg_img }}" alt="">
                                <p class="l-title">{{ foo.proj_name }}</p>
                                <p class="l-difficulty"><span>{{ foo.get_proj_level_display }}</span><span
                                        class="glyphicon glyphicon-user"></span><span>{{ foo.proj_student }}</span></p>
                            </a>
                        {% endfor %}
                    </div>
                    <div id="l-sec-btnLeft" class="iconfont l-sec-btnLeft">&#xe659;</div>
                    <div id="l-sec-btnRight" class="iconfont  l-sec-btnRight">&#xe658;</div>
                </div>
            </div>

             <div class="cha-inner-list">
                <p class="cha-name">课程评论</p>
                <ul class="list-group cha-list-color list_border">
                    {% for tex in contacts %}
                        <li class="list-group-item course-comment">
                            <span>{{ tex.user.nick_name }}:</span><span>{{ tex.comment }}</span>
                        </li>
                    {% endfor %}
                </ul>
            </div>
        </div>


    </div>
{% endblock %}

{% block small_js %}
    <script src="{% static 'jquery/chapterList.js' %}"></script>
    <script type="text/javascript" src="{% static 'jquery/paging/pageMe.js' %}"></script>
    <script>
        // pageMe.js 使用方法
        var page = $("#page");
        page.paging({
            pageNum: 1, // 当前页面
            totalNum: parseInt(page.attr('allpage')), // 总页码
            totalList: parseInt(page.attr('allnum')), // 记录总数量
            callback: function (num) { //回调函数
                console.log(num);
                $.ajax({
                        url: '{% url "chapter_ajax" %}',    //请求的url地址
                        dataType: "json",   //返回格式为json
                        async: true,//请求是否异步，默认为异步，这也是ajax重要特性
                        data: {"id": "value",'csrfmiddlewaretoken': '{{ csrf_token  }}'},    //参数值
                        type: "POST",   //请求方式
                        beforeSend: function () {
                            //请求前的处理
                        },
                        success: function (req) {
                            //请求成功时处理
                            alert(1)

                        },
                        complete: function () {
                            //请求完成的处理
                            alert(2)
                        },
                        error: function () {
                            //请求出错处理
                            alert(3)
                        }
            });
                {#$.post('{% url "chapter_ajax" %}', {#}
                {#    'a': 1,#}
                {#    "b": 2,#}
                {#    'csrfmiddlewaretoken': '{{ csrf_token  }}'#}
                {#    console.log('res')#}
                {#    console.log('res')#}
                {#    console.log('res')#}

            }
        });
    </script>
{% endblock %}

templates/course/courseList.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block title %}
    课程章节
{% endblock %}

{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/course/courseList.css' %}">
{% endblock %}

{% block html_body %}
    <div class="c-nav">
        <div class="container">
            <ul class="list-group c-ul">
                <li class="list-group-item c-li c-li-border">
                    <div class="row">
                        <span class="c-li-bold">方向：</span>
                        <span class="c-li-hover">全部</span>
                        <span class="c-li-hover green-span c-li-hover">前端开发</span>
                        <span class="c-li-hover">后端开发</span>
                        <span class="c-li-hover">移动开发</span>
                        <span class="c-li-hover">算法&数学</span>
                        <span class="c-li-hover">前沿技术</span>
                        <span class="c-li-hover">云计算&大数据</span>
                        <span class="c-li-hover">运维&测试</span>
                        <span class="c-li-hover">数据库</span>
                        <span class="c-li-hover">UI设计&多媒体</span>
                        <span class="c-li-hover">游戏</span>
                    </div>
                </li>

                <li class="list-group-item c-li c-li-border">
                    <div class="row">
                        <span class="c-li-bold">分类：</span>
                        <span class="c-li-hover">全部</span>
                        <span class="c-li-hover">HTML/CSS</span>
                        <span class="c-li-hover">JavaScript</span>
                        <span class="c-li-hover">Vue.js</span>
                        <span class="c-li-hover  green-span c-li-hover">React.JS</span>
                        <span class="c-li-hover">Angular</span>
                        <span class="c-li-hover">Node.js</span>
                        <span class="c-li-hover">jQuery</span>
                        <span class="c-li-hover">Bootstrap</span>
                        <span class="c-li-hover">Sass/Less</span>
                        <span class="c-li-hover">WebApp</span>
                        <span class="c-li-hover">小程序</span>
                        <span class="c-li-hover">前端工具</span>
                        <span class="c-li-hover">CSS</span>
                        <span class="c-li-hover">Html5</span>
                        <span class="c-li-hover">CSS3</span>
                    </div>
                </li>
                <li class="list-group-item c-li">
                    <div class="row">
                        <span class="c-li-bold">难度：</span>
                        <span class="c-li-hover">全部</span>
                        <span class="c-li-hover green-span c-li-hover">入门</span>
                        <span class="c-li-hover">初级</span>
                        <span class="c-li-hover">中级</span>
                        <span class="c-li-hover">高级</span>
                    </div>
                </li>
            </ul>
        </div>
    </div>
    <div class="container-fluid context">
        <div class="container">
            <p class="l-nav"><a class="l-nav-ban">最新</a><a>最热</a></p>
            <div class="row">
                {% for course in data %}
                    <a href="{% url 'chapter_list' course.id %}" class="col-md-3 l-sec">
                        <img src="{{ MEDIA_URL }}{{ course.cover }}  " alt="">
                        <span class="l-title">{{ course.name }}</span>
                        <p class="l-difficulty"><span>{{ course.get_leave_display }}</span><span
                                class="glyphicon glyphicon-user"></span><span>{{ course.study_len }}</span></p>
                        <p class="l-text">{{ course.synopsis }}</p>
                    </a>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}