apps/blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path

from blog.views import BlogView, BlogListView

app_name = '[blog]'
urlpatterns = [
    # path('', admin.site.urls),
    path('', BlogListView.as_view(), name="bloglist"),
    re_path(r'^blog/(?P<title>.*)$', BlogView.as_view(), name="blog"),
]

huima/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.urls import re_path
from django.views.static import serve
from .settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.index.urls', 'index'), namespace='index')),  # wjl
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('course/', include('apps.course.urls')),
    path('subject/', include('apps.subject.urls')),
    path('task/', include('apps.task.urls')),
    path('usercenter/', include('apps.user.urls')),
    re_path(r"media/(?P<path>.*)$", serve, {'document_root': MEDIA_ROOT}),

]

apps/blog/models.py
from django.db import models
from user.models import *

# Create your models here.


class Blog(models.Model):
    '''博客表'''

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="博主id")
    level = models.ForeignKey(Level, on_delete=models.CASCADE, verbose_name="分类id")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="语言id")
    title = models.CharField(max_length=256, verbose_name="标题")
    front_image = models.ImageField(upload_to="blog/%Y/%m", verbose_name="博客封面图",default='')
    content = models.TextField(verbose_name="正文")
    publish = models.DateTimeField(auto_now=True, verbose_name="发布时间")
    com_num = models.IntegerField(default=0, verbose_name="评论数")
    tag_num = models.IntegerField(default=0, verbose_name="点赞数")

    def __str__(self):
        return "%s - %s" % (self.user, self.title)

    class Meta:
        ordering = ['publish']
        verbose_name = '博客表'
        verbose_name_plural = verbose_name


class BlogComment(models.Model):
    '''博客回复表'''

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户")
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, verbose_name="回复博客")
    content = models.TextField(verbose_name="回复内容")
    publish = models.DateTimeField(auto_now=True, verbose_name="回复时间")
    tag_num = models.IntegerField(default=0, verbose_name="点赞数")

    def __str__(self):
        return "%s - %s" % (self.user, self.blog)

    class Meta:
        ordering = ['publish']
        verbose_name = '博客回复表'
        verbose_name_plural = verbose_name

apps/blog/views.py
from django.shortcuts import render

# Create your views here.
from django.views import View
from blog.models import Blog, BlogComment
from django.db.models import Q


class BlogListView(View):
    def get(self, request):
        blogs = Blog.objects.all().order_by('-publish')
        # level = request.GET.get()
        # category = request.GET.get()
        return render(request, 'blog/bloglist.html', locals())


class BlogView(View):
    def get(self, request, title):
        blog = Blog.objects.get(title=title)
        comments = BlogComment.objects.filter(blog=blog.id)
        return render(request, 'blog/blog.html', locals())

templates/blog/blog.html
{% extends 'base.html' %}{% load staticfiles %}
{% block title %}{{ blog.title }}{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/blog.css' %}">
{% endblock %}
{% block html_body %}
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{% url 'blog:bloglist' %}">所有文章</a></li>
            <li><a href="#">{{ blog.level }}</a></li>
            <li><a href="#">{{ blog.category }}</a></li>
            <li class="active">{{ blog.title }}</li>
        </ol>
    </div>
    <section class="blog-home">
        <div class="container">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8 mx-auto">
                    <div class="post post-card">
                        <div class="single-post-header">
                            <ul class="list-inline blog-item-links">
                                <li class="list-inline-item"><a href="#">{{ blog.category }}</a></li>
                                <li class="list-inline-item"><a href="#">{{ blog.level }}</a></li>
                                <li class="list-inline-item"><a href="#">{{ blog.publish }}</a></li>
                            </ul>
                            <h1>{{ blog.title }}</h1>
                        </div>
                        <a href="#" class="post-image"><img src="{% static 'images/blog/test1.jpg' %}" alt="#"
                                                            class="img-fluid featured-img"></a>
                        <div class="row">
                            <div class="col-12">
                                <div class="card-details">
                                    <p>{{ blog.content|safe }}</p>
                                    <p>有什么你最喜欢的用于业余项目的 Python 库不在这个列表中吗？请在评论中和我们分享。</p>
                                </div>
                            </div>
                        </div>
                        <ul class="list-inline share-icon text-left">
                            <li class="list-inline-item"><span class="glyphicon glyphicon-thumbs-up"></span>
                                点赞 {{ blog.tag_num }}次
                            </li>
                            <li class="list-inline-item"><span class="glyphicon glyphicon-comment"></span>
                                评论 {{ blog.com_num }}条
                            </li>
                        </ul>
                    </div>
                    <div class="post-writer">
                        <div class="media d-flex align-items-center">
                            <div class="row">
                                <div class="col-lg-3">
                                    <a href="#"><img class="mr-5" src="{{ MEDIA_URL }}{{ blog.user.avatar }}" alt="Admin"></a>
                                </div>
                                <div class="col-lg-9">
                                    <div class="media-body">
                                        <h5 class="mt-0"><a href="#">{{ blog.user.username }}</a></h5>
                                        <p>{{ blog.user.description }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="all-comments contact">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8 mx-auto">
                    <div class="comment-posts">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class=""><h2 class="comment-section-title">评论区</h2></div>
                                {% for comment in comments %}
                                    <div class="media single-content">
                                        <div class="row">
                                            <div class="col-lg-1">
                                                <a href="#"><img class=" img-responsive"
                                                                 src="{{ MEDIA_URL }}{{ comment.user.avatar }}"
                                                                 alt="image"></a>
                                            </div>
                                            <div class="col-lg-11">
                                                <div class="media-body">
                                                    <h3 class="">{{ comment.user.username }} |
                                                        <span>{{ comment.publish }}</span></h3>
                                                    <p>{{ comment.content }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-12">
                                <div class="border-wrapper"><h2 class="comment-section-title">发表评论</h2></div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <label class="sr-only">Massage</label>
                                    <textarea class="form-control textarea" name="message" rows="5"
                                              placeholder="Massage"></textarea>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <div class="text-right">
                                        <button type="submit" class="btn btn-secondary">发送</button>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/blog/bloglist.html
{% extends 'base.html' %}{% load staticfiles %}
{% block title %}博客列表{% endblock %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/bloglist.css' %}">
{% endblock %}
{% block html_body %}

    <div class="container">
        <ul class="nav nav-tabs">
            <li role="presentation"><a href="#">所有文章</a></li>
            <li role="presentation" class="active"><a href="#">最新文章</a></li>
            <li role="presentation"><a href="#">IT职场</a></li>
            <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                   aria-expanded="false" onclick="return false">
                    前端 <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#">JavaScript</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">HTML5</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">CSS</a></li>
                </ul>
            </li>
            <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                   aria-expanded="false" onclick="return false">
                    后端 <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#">Python</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Java</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">C/C++</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">PHP</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">.NET</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Ruby</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Go</a></li>
                </ul>
            </li>
            <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                   aria-expanded="false" onclick="return false">
                    移动端 <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#">Android</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">iOS</a></li>
                </ul>
            </li>
            <li role="presentation"><a href="#">数据库</a></li>
            <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                   aria-expanded="false" onclick="return false">
                    运维 <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#">Linux</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">UNIX</a></li>
                </ul>
            </li>
            <li role="presentation" class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                   aria-expanded="false" onclick="return false">
                    其他技术 <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                    <li><a href="#">Git</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">机器学习</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">算法</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">测试</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">信息安全</a></li>
                    <li role="separator" class="divider"></li>
                    <li><a href="#">Vim</a></li>
                </ul>
            </li>
        </ul>
        <br>
        <ol class="breadcrumb">
            <li><a href="#">所有文章</a></li>
            <li class="active">最新文章</li>
        </ol>
    </div>
    <br>
    <section class="blog-page-1">
        <div class="container">
            <div class="row">
                {% for blog in blogs %}
                    <div class="col-lg-4 col-sm-6 col-md-6">
                        <div class="blog-post">
                            <div class="post-img">
                                <img src="{% static 'images/blog/test1.jpg' %}" alt="">
                            </div>
                            <div class="blog-details">
                                <a href="{% url 'blog:blog' blog.title %}">
                                    <h4 class="media-heading">{{ blog.title }}</h4>
                                </a>
                                <p class="notice">{{ blog.content }}</p>
                                <ul class="list-inline blog-item-links">
                                    <li class="list-inline-item">
                                        <span class="glyphicon glyphicon-user"></span><a
                                            href="#"> {{ blog.user.username }}</a>
                                    </li>
                                    <li class="list-inline-item">
                                        <span class="glyphicon glyphicon-calendar"></span> {{ blog.publish }}
                                    </li>
                                    <li class="list-inline-item">
                                        <span class="glyphicon glyphicon-education"></span> {{ blog.category }} {{ blog.level }}
                                    </li>
                                    <li class="list-inline-item">
                                        <span class="glyphicon glyphicon-comment"></span> 评论 {{ blog.com_num }}条
                                    </li>
                                    <li class="list-inline-item">
                                        <span class="glyphicon glyphicon-thumbs-up"></span> 点赞 {{ blog.tag_num }}次
                                    </li>
                                </ul>
                                <p></p>
                                <a class="blog-post-link" href="{% url 'blog:blog' blog.title %}">
                                    <span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span> 阅读全文
                                </a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
    <div class="text-center">
        <nav aria-label="Page navigation">
            <ul class="pagination">
                <li>
                    <a href="#" aria-label="Previous">
                        <span aria-hidden="true">&laquo;</span>
                    </a>
                </li>
                <li><a href="#">1</a></li>
                <li><a href="#">2</a></li>
                <li><a href="#">3</a></li>
                <li><a href="#">4</a></li>
                <li><a href="#">5</a></li>
                <li>
                    <a href="#" aria-label="Next">
                        <span aria-hidden="true">&raquo;</span>
                    </a>
                </li>
            </ul>
        </nav>
    </div>
    <script>
        $('.dropdown-toggle').on("click", function () {
            console.log('test')
            $(".dropdown-toggle").dropdown('toggle');
        })
        $('li.dropdown').mouseover(function () {
            $(this).addClass('open');
        }).mouseout(function () {
            $(this).removeClass('open');
        });

        $(function () {
            $('.popover-toggle').popover('toggle');
        });
        $('button.popover-toggle').mouseover(function () {
            $(this).addClass('click');
        }).mouseout(function () {
            $(this).removeClass('click');
        });
    </script>
    <script>
        $("[t='popover']").on("click mouseenter", function (e) {
            e.stopPropagation();
            var $this = $(this);
            $this.popover("show");
            $(document).one("click", function () {
                $this.popover("hide");
            });
            $(".popover").on("click", function (e) {
                e.stopPropagation();
            });
        });
    </script>
{% endblock %}