apps/blog/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import re_path

from blog.views import BlogView, BlogListView

app_name = '[blog]'
urlpatterns = [
    # path('', admin.site.urls),
    path('', BlogListView.as_view(), name="bloglist"),
    re_path(r'^blog/(?P<title>.*)$', BlogView.as_view(), name="blog"),
]

apps/index/urls.py
from django.contrib import admin
from django.urls import path
from index.views import *

app_name = '[index]'
urlpatterns = [
    path('', show_index, name='index1'),
    path('login', LoginView.as_view(), name='login'),
    path('register', Register.as_view(), name='register')
]

huima/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.urls import re_path
from django.views.static import serve
from .settings import MEDIA_ROOT

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('apps.index.urls', 'index'), namespace='index')),  # wjl
    path('blog/', include('apps.blog.urls', namespace='blog')),
    path('course/', include('apps.course.urls')),
    path('subject/', include('apps.subject.urls')),
    path('task/', include('apps.task.urls')),
    path('usercenter/', include('apps.user.urls')),
    re_path(r"media/(?P<path>.*)$", serve, {'document_root': MEDIA_ROOT}),

]

templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block custom_title %}慧码时代{% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="{% static 'bootstrap/bootstrap.css' %}">
	<script src="{% static 'jquery/jquery-3.1.1.js' %}"></script>
    {% block custom_css %}{% endblock %}
    {% block custom_js %}{% endblock %}
    <link rel="stylesheet" href="{% static 'css/nav.css' %}">
</head>
<body ondragstart="return false">
<!-- 导航条 -->
<nav class="navbar navbar-default nav_height">
  <div class="container-fluid nav_panel">
    <div class="navbar-header nav_head">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
{#      <a class="navbar-brand" href="#"></a>#}
        <a href="{% url "index:index1" %}"><h1 style="">慧码时代</h1></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse nav_body" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-left">
        <li class="active"><a href="{% url "index:index1" %}">首页</a></li>
        <li><a href="{% url "chapter" 1 %}">课程中心</a></li>
        <li><a href="{% url "blog:bloglist" %}">博客</a></li>
        <li><a href="{% url "project_list"  "page=1" %}">项目</a></li>
        <li><a href="{% url "[usercenter]:course" %}">个人中心</a></li>
      </ul>
      
      <ul class="nav navbar-nav nav-magrig navbar-right ">
          {% if request.user.is_authenticated %}
            <li style="width: 100px;white-space: nowrap;overflow:hidden;"><a href="/usercenter"><img
                    src="{{ MEDIA_URL }}{{ request.user.avatar }}" alt=""
                    style="width: 20px; height: 20px; margin-top: -5px;">&nbsp;&nbsp;{{ request.user.nick_name }}
            </a></li>
            <li><a href="">退出</a></li>
          {% else %}
            <li><a href="#" data-toggle="modal" data-target=".bs-example-modal-sm">登录</a></li>
            <li><a href="#">注册</a></li>
          {% endif %}
      </ul>

 	<form class="navbar-form navbar-right form-search">
 			<div class="search-border">
		        <div class="form-group">
		          	<input type="text" class="form-control from-defined" placeholder="Search">
		        </div>
		        	<a href=""><span class="iconfont">&#xe603;</span></a>
	        </div>
    </form>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
 </nav>

<!-- 模态框 -->
	<div class="modal fade bs-example-modal-sm" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
	  <div class="modal-dialog modal-sm" role="document">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title" id="myModalLabel">登录</h4>
	      </div>
	      <div class="modal-body">
	        <form class="form-horizontal" id="jsSubForm">
                {% csrf_token %}
			  <div class="form-group">
			    <label class="col-sm-3 col-md-3 control-label">账号：</label>
			    <div class="col-sm-9 col-md-9 input-wei">
			      <input type="text" class="form-control" name="username" id="username" placeholder="邮箱/电话">
			    </div>
			  </div>
			  <div class="form-group">
			    <label class="col-sm-3 col-md-3 control-label">密码：</label>
			    <div class="col-sm-9 col-md-9 input-wei">
			      <input type="password" name="password" id="password" class="form-control"  placeholder="密码">
			    </div>
			  </div>
			  <div class="form-group">
			    <div class="col-sm-offset-2 col-sm-10">
			      <div class="checkbox">
			        <label>
			          <input type="checkbox"> 记住密码
			        </label>
			      </div>
			    </div>
			  </div>
			</form>
	      </div>
	      <div class="modal-footer">
              <button type="button" class="btn btn-success" id="jsSubBtn">登录</button>
              <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
	      </div>
	    </div>
	  </div>
	</div>

{% block html_body %}
{% endblock %}



<footer>
	<div class="footer_body">蜀备ICP 慧码时代&copy; 5215584886号</div>
</footer>
</body>
{% block small_js %}{% endblock %}
<script src="{% static 'bootstrap/bootstrap.min.js' %}"></script>
<script src="{% static 'chart/Chart.bundle.js' %}"></script>
<script src="{% static 'chart/chart.dinyi.js' %}"></script>
<script>
    $(function () {
       $('#jsSubBtn') .on('click',function () {
           $.ajax({
               cache:false,
               type:"POST",
               url:"{% url 'index:login' %}",
               data:$('#jsSubForm').serialize(),
               async:true,
               success:function (data) {
                   if (data.status == 'success') {
                       window.location.reload();
                   }else if(data.status == 'fail'){
                       alert_danger = "<div class=\"alert alert-danger\" role=\"alert\">" + data.msg +
                           "是否<a href=\"#\" class=\"alert-link\">忘记密码</a>？" +
                           "</div>";
                       $('#jsSubForm').prepend(alert_danger);
                   }
               }
           })
       })
    })
</script>
</html>

templates/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block custom_css %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
    <link rel="stylesheet" href="{% static 'css/easyform.css' %}">
{% endblock %}
{% block custom_js %}
    <script type="text/javascript" src="{% static 'js/easyform.js' %}"></script>
{% endblock %}
{% block html_body %}
	<div class="container">
		<div class="row register_header">
			<div class="col-md-4 title_sty">
				<label class="h1">慧码时代</label><label class="h2">|用户注册</label>
			</div>
			<div class="col-md-8"></div>
		</div>
		<div class="row register_body" style="margin-top: 50px;">
			<div class="col-md-5 register_mod">
				<form class="form-horizontal" id="registerForm" name="registerForm">
                    {% csrf_token %}
				  <div class="form-group">
				    <label for="name" class="col-sm-3 control-label">昵称：</label>
				    <div class="col-sm-9 padd-right">
				      <input type="text" class="form-control" id="Nickname" name="Nickname"
                             message="昵称为1-4位中文、英文、数字、下划线、中文标点符号"
                             easyform="char-chinese;length:1-4;real-time"
                             easytip="disappear:lost-focus;theme:red;" placeholder="请输入你的昵称">
				    </div>
				  </div>
				  <div class="form-group">
				    <label class="col-sm-3 control-label">性别：</label>
				    <div class="col-sm-9 padd-right">
					    <label class="radio-inline">
						  <input type="radio" name="Sex" class="css-checkbox" id="sex-1" value="male"> 男
						</label>
						<label class="radio-inline">
						  <input type="radio" name="Sex" class="css-checkbox" id="sex-2" value="female"> 女
						</label>
				    </div>
				  </div>
				  <div class="form-group">
				    <label class="col-sm-3 control-label">生日：</label>
				    <div class="col-sm-9 padd-right">
				      <input type="date" class="form-control" id="birthday" name="Birthday"
                             message="选择出生日期"
                             easyform="date;real-time"
                             easytip="disappear:lost-focus;theme:red;">
				    </div>
				  </div>
				  <div class="form-group">
				    <label class="col-sm-3 control-label">签名：</label>
				    <div class="col-sm-9 padd-right">
				      <textarea class="form-control" rows="3" name="Signature" placeholder="添加你的签名"></textarea>
				    </div>
				  </div>
{#				  <div class="form-group">#}
{#				    <label class="col-sm-3 control-label">电话号码：</label>#}
{#				    <div class="col-sm-7 padd-right">#}
{#				      <input type="text" class="form-control"  placeholder="输入你的手机号码">#}
{#				    </div>#}
{#				    <button type="button" class="col-sm-3 btn btn-info">发送</button>#}
{#				  </div>#}
{#				  <div class="form-group">#}
{#				    <label class="col-sm-3 control-label">验证码：</label>#}
{#				    <div class="col-sm-9 padd-right">#}
{#				      <input type="text" class="form-control" id="auth_code" placeholder="输入手机验证码">#}
{#				    </div>#}
{#				  </div>#}
				  <div class="form-group">
				    <label class="col-sm-3 control-label">邮箱：</label>
				    <div class="col-sm-9 padd-right">
				      <input type="email" class="form-control" name="Username"
                             id="inputEmail"
                             placeholder="输入你的邮箱"
                             message="邮箱格式错误"
                             easyform="email;real-time"
                             easytip="disappear:lost-focus;theme:red;">
				    </div>
				  </div>
				  <div class="form-group">
				    <label for="password" class="col-sm-3 control-label">密码：</label>
				    <div class="col-sm-9 padd-right">
				      <input type="password" class="form-control" id="repassword" name="repassword"
                             placeholder="输入你的密码"
                             message="密码必须为6—16位"
                             easyform="length:6-16;char-normal;real-time;"
                             easytip="disappear:lost-focus;theme:red;">
				    </div>
				  </div>
				  <div class="form-group">
				    <label for="password2" class="col-sm-3 control-label">确认密码：</label>
				    <div class="col-sm-9 padd-right">
				      <input type="password" class="form-control" id="password1" name="Password"
                             placeholder="输入你的密码"
                             message="密码不一致"
                             easyform="equal:#repassword;real-time;"
                             easytip="disappear:lost-focus;theme:red;">
				    </div>
				  </div>
				  <div class="form-group">
				    <div class="col-sm-offset-2 col-sm-10">
				      <input type="submit" id="registerBtn" class="btn btn-success" style="width: 80%" value="注册">
				    </div>
				  </div>
				</form>
			</div>
		</div>
	</div>
    {% block small_js %}
    <script type="text/javascript">

	</script>
        <script>
         $(document).ready(function(){
            var ef = $('#registerForm').easyform();
            $(function () {
               $('#registerBtn') .on('click',function () {
                   ef.success = function(ef){
                   $.ajax({
                       cache:false,
                       type:"POST",
                       url:"{% url 'index:register' %}",
                       data:$('#registerForm').serialize(),
                       async:false,
                       success:function (data) {
                           if (data.status == 'success') {
                               alert("注册成功");
                               {#window.location.reload();#}

                           }else if(data.status == 'fail'){
                               alert(data.msg);
                               {#$('#registerForm').prepend(alert_danger);#}
                           }
                       }
                   })}
               })
            })
       });
    </script>

    {% endblock %}
{% endblock %}